version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types: [minor, patch]
      eslint-major:
        patterns: [eslint, "@eslint/js"]
        update-types: [major]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types: [minor, patch]
      major:
        update-types: [major]
